[project]
name = "llmcompiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "bs4==0.0.1",
    "langchain==0.2.6",
    "langchain-community==0.2.6",
    "numexpr==2.8.7",
    "openai<1.0",
    "tiktoken==0.5.2",
    "pydantic<2",
]
